---
- main: Installing...
  hosts: staging_ALL
  become: yes

  tasks:
  - name: Update and Upgrade system
    apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

  - name: Install MySQL
    apt: name: mysql-server state=latest

  


